### PR TITLE
Implement checks that I have made

### PR DESCRIPTION
**Pull request by Hans5958**
I have implemented some of the checks that I made for [Hans5958/PreMiD-MTS](https://github.com/Hans5958/PreMiD-MTS) in this pull request, along with some minor typo fixes.

_First issue/pull request!_

### CODE REVIEW

**Comment by LewisTehMinerz** [comment]
Hi! Thanks for helping out!

I recently added a CI check in the Presences repository to validate metadata.json so I'm not sure if the script is necessary anymore, however the regexes you've provided look to be very useful. Have you tested using them on multiple metadata files just to make sure that it won't fail the tests?

**Comment by Hans5958** [comment]
> 
> 
> Hi! Thanks for helping out!
> 
> ~I recently added a CI check in the Presences repository to validate metadata.json so I'm not sure if the script is necessary anymore~ (misread, ignore me), however the regexes you've provided look to be very useful. Have you tested using them on multiple metadata files just to make sure that it won't fail the tests?

[Let just say](https://github.com/Hans5958/PreMiD-MTS/releases/tag/1.0.0) that Bas950 asked me to test all the presence on the repository so he can fix it. Nonetheless, I also make another changes recently and have tested all of them. Going to test again before releasing version 1.1.0 of PreMiD-MTS.

**Comment by LewisTehMinerz** [comment]
I've just ran the schema validator using the new schema and 3 presences failed for the exact same reason:

`✘ Kodi (does not match pattern "^([a-z0-9-]+\\.)*[0-9a-z_-]+(\\.[a-z]+)+$" @ instance.url[0])`
`✘ VLC (does not match pattern "^([a-z0-9-]+\\.)*[0-9a-z_-]+(\\.[a-z]+)+$" @ instance.url[0])`
`✘ WIMS (does not match pattern "^([a-z0-9-]+\\.)*[0-9a-z_-]+(\\.[a-z]+)+$" @ instance.url[1])`

These are all presences that have IP addresses or `localhost`/`127.0.0.1` as their URLs, which are perfectly valid. This is why I left out the regex for URLs.

**Comment by Hans5958** [comment]
> 
> 
> I've just ran the schema validator using the new schema and 3 presences failed for the exact same reason:
> 
> `✘ Kodi (does not match pattern "^([a-z0-9-]+\\.)*[0-9a-z_-]+(\\.[a-z]+)+$" @ instance.url[0])`
> `✘ VLC (does not match pattern "^([a-z0-9-]+\\.)*[0-9a-z_-]+(\\.[a-z]+)+$" @ instance.url[0])`
> `✘ WIMS (does not match pattern "^([a-z0-9-]+\\.)*[0-9a-z_-]+(\\.[a-z]+)+$" @ instance.url[1])`
> 
> These are all presences that have IP addresses or `localhost`/`127.0.0.1` as their URLs, which are perfectly valid. This is why I left out the regex for URLs.

Yeah, just noticed about that seconds before reading it. Will fix it.

**Comment by Hans5958** [comment]
Okay, I think I fixed the regex, but somehow Bash didn't like the pattern and fails it, even though RegExr passed it.

``^(([a-z0-9-]+\\.)*[0-9a-z_-]+(\\.[a-z]+)+|(\\d{1,3}\\.){3}\\d{1,3}|localhost)$``

You need to double-check it. The script will pass if the pattern is this: ````

**Comment by LewisTehMinerz** [comment]
I've confirmed that the script now throws no validation errors. Looks good. Merging.

**Comment by Hans5958** [comment]
thanks

**Pull request merged**
